name: Build and Deploy Nextra Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: |
        npm run build
        touch out/.nojekyll

    - name: Deploy
      env:
        PERSONAL_TOKEN: ${{ secrets.GH_PAGES }}
      run: |
        git config --global user.name "ywarnecke"
        git config --global user.email "yannik.warnecke@uni-muenster.de" 
        git remote set-url origin https://ywarnecke:${PERSONAL_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "ywarnecke <yannik.warnecke@uni-muenster.de>"
